In [1]:

from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np

In [2]:
iris = datasets.load_iris()
X=iris.data
y=iris.target


In [3]:
y[:5]

array([0, 0, 0, 0, 0])

In [4]:
X[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

Separar entrenamiento y prueba

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size
=0.3)

Ajustar el escalador a los datos de entrenamiento

In [11]:
sc=StandardScaler()
X_train_std=sc.fit_transform(X_train)

Aplicar el escalador a los datos de prueba.

In [12]:
X_test_std=sc.transform(X_test)

Se crea un objeto perceptrón con los parámetros: 40 iteraciones sobre los datos, y una
tasa de aprendizaje de 0.1.

In [13]:
ppn = Perceptron(max_iter=40, eta0=0.1, random_state=0)

Se entrena el perceptrón.

In [14]:
ppn.fit(X_train_std, y_train)

Perceptron(eta0=0.1, max_iter=40)

Se aplica el perceptrón entrenado en los datos de X para hacer predicciones para los
datos de prueba y

In [15]:
y_pred = ppn.predict(X_test_std)

Ver los datos predichos de prueba y.

In [16]:
y_pred

array([2, 2, 1, 0, 2, 2, 0, 0, 0, 0, 2, 2, 2, 1, 0, 2, 2, 1, 2, 2, 2, 2,
       2, 1, 2, 1, 0, 2, 1, 0, 0, 2, 0, 0, 2, 1, 2, 2, 0, 2, 0, 1, 1, 1,
       2])

Ver los datos reales de prueba y.

In [17]:
y_test

array([2, 2, 1, 0, 2, 2, 0, 0, 0, 0, 1, 2, 1, 1, 0, 2, 2, 1, 2, 2, 1, 1,
       1, 1, 2, 1, 0, 2, 1, 0, 0, 2, 0, 0, 2, 1, 1, 2, 0, 2, 0, 1, 1, 1,
       1])

Ver la precisión del modelo, que es: 1 - (observaciones predicen observaciones
incorrectas / totales).

In [18]:
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))

Accuracy: 0.84
